version: '3.8'

services:
  users:
    build: ./user_service
    ports:
      - "8000:8000"
    networks:
      - graphql-network

  tasks:
    build: ./task_service
    ports:
      - "8800:8800"
    networks:
      - graphql-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - users
      - tasks
    networks:
      - graphql-network

networks:
  graphql-network:
    driver: bridge
